### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by rbcuenca** [Insper/SAME70-examples#29]
Dizem que Rust é a linguagem do futuro para sistemas embarcados e parece que já da para rodar na nossa placa.

https://github.com/atsams-rs/atsamx7x-rust

**Comment by Kcpf** [comment]
Estou fazendo esse junto com o openocd!

**Comment by rafaelcorsi** [comment]
@Kcpf atualizei para A, se você refizer o lab 2 criando as APIs para o PIO.
